import { Severity } from '@/types/incident';

export interface NotificationPayload {
  incidentId: string;
  title: string;
  severity: Severity;
  status: string;
  eventType: 'INCIDENT_CREATED' | 'SEVERITY_CHANGED' | 'FACT_CONFIRMED' | 'DECISION_MADE' | 'INCIDENT_RESOLVED';
  message: string;
  timestamp: string;
  commander?: string;
  url?: string;
}

export class NotificationService {
  private slackWebhookUrl: string;

  constructor() {
    this.slackWebhookUrl = process.env.SLACK_WEBHOOK_URL || '';
  }

  buildSlackBlocks(payload: NotificationPayload) {
    const severityColors: Record<string, string> = {
      SEV1: '🚨 *[SEV1 - CRITICAL OUTAGE]*',
      SEV2: '⚠️ *[SEV2 - MAJOR DEGRADATION]*',
      SEV3: '🟡 *[SEV3 - MINOR ISSUE]*',
      SEV4: 'ℹ️ *[SEV4 - INFORMATIONAL]*',
    };

    return {
      text: `${severityColors[payload.severity] || payload.severity} ${payload.title}`,
      blocks: [
        {
          type: 'header',
          text: {
            type: 'plain_text',
            text: `Incident Alert: ${payload.title}`,
            emoji: true,
          },
        },
        {
          type: 'section',
          fields: [
            {
              type: 'mrkdwn',
              text: `*Severity:*\n${payload.severity}`,
            },
            {
              type: 'mrkdwn',
              text: `*Status:*\n${payload.status}`,
            },
            {
              type: 'mrkdwn',
              text: `*Event:*\n${payload.eventType}`,
            },
            {
              type: 'mrkdwn',
              text: `*Incident ID:*\n\`${payload.incidentId}\``,
            },
          ],
        },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `*Details:*\n${payload.message}`,
          },
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `Generated by AI Incident Commander at ${new Date(payload.timestamp).toUTCString()}`,
            },
          ],
        },
      ],
    };
  }

  async dispatchNotification(payload: NotificationPayload): Promise<{ success: boolean; delivered: boolean; error?: string }> {
    if (!this.slackWebhookUrl) {
      // In sandbox/mock mode, simulate successful dispatch
      console.log('[NotificationService (Sandbox)] Dispatching incident notification:', payload);
      return { success: true, delivered: false };
    }

    try {
      const slackBody = this.buildSlackBlocks(payload);
      const res = await fetch(this.slackWebhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(slackBody),
      });

      if (!res.ok) {
        throw new Error(`Slack webhook responded with status ${res.status}`);
      }

      return { success: true, delivered: true };
    } catch (err: any) {
      console.error('[NotificationService] Failed to send Slack webhook notification:', err);
      return { success: false, delivered: false, error: err.message };
    }
  }
}

export const notificationService = new NotificationService();
export default notificationService;
